name: figma_auto_layout
description: A replicate of Figma's auto layout feature that makes converting Figma designs to code faster and less error prone.
version: 0.0.1
homepage: https://github.com/JakesMD/flutter_figma_auto_layout
repository: https://github.com/JakesMD/flutter_figma_auto_layout


environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  signed_spacing_flex: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
